#Chapter 2 Numpy

Let's start with creating NumPy arrays.

In [7]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)

# Creating an array of zeros
zeros_arr = np.zeros((2, 3))
print("\nArray of zeros:\n", zeros_arr)

# Creating an array of ones
ones_arr = np.ones((3, 2))
print("\nArray of ones:\n", ones_arr)

# Creating an identity matrix
identity_matrix = np.eye(3)
print("\nIdentity matrix:\n", identity_matrix)

1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Now let's look at some basic array operations.

In [8]:
# Basic arithmetic operations
arr = np.array([10, 20, 30, 40])
print("Original array:", arr)
print("Array + 5:", arr + 5)
print("Array * 2:", arr * 2)
print("Array squared:", arr**2)

# Element-wise operations
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
print("\nArray a:", arr_a)
print("Array b:", arr_b)
print("a + b:", arr_a + arr_b)
print("a * b:", arr_a * arr_b)

Original array: [10 20 30 40]
Array + 5: [15 25 35 45]
Array * 2: [20 40 60 80]
Array squared: [ 100  400  900 1600]

Array a: [1 2 3]
Array b: [4 5 6]
a + b: [5 7 9]
a * b: [ 4 10 18]


Indexing and slicing in NumPy.

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)

# Accessing elements
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing arr[start:stop:step]
print("Elements from index 2 to 5:", arr[2:6])
print("Elements from beginning to index 4:", arr[:5])
print("Elements from index 5 to the end:", arr[5:])
print("Every other element:", arr[::2])

# Indexing in 2D arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:\n", arr_2d)
print("Element at row 1, column 2:", arr_2d[1, 2])
print("First row:", arr_2d[0, :])
print("Third column:", arr_2d[:, 2])

Original array: [ 1  2  3  4  5  6  7  8  9 10]
First element: 1
Last element: 10
Elements from index 2 to 5: [3 4 5 6]
Elements from beginning to index 4: [1 2 3 4 5]
Elements from index 5 to the end: [ 6  7  8  9 10]
Every other element: [1 3 5 7 9]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
First row: [1 2 3]
Third column: [3 6 9]


Shape manipulation and data types.

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", arr)
print("Shape:", arr.shape)

# Reshaping the array
reshaped_arr = arr.reshape(3, 2)
print("\nReshaped array:\n", reshaped_arr)
print("New shape:", reshaped_arr.shape)

# Transposing the array
transposed_arr = arr.T
print("\nTransposed array:\n", transposed_arr)
print("Transposed shape:", transposed_arr.shape)

# Data types
print("\nData type of the array:", arr.dtype)

# Changing data type
float_arr = arr.astype(np.float64)
print("\nArray with float data type:\n", float_arr)
print("New data type:", float_arr.dtype)

Original array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
New shape: (3, 2)

Transposed array:
 [[1 4]
 [2 5]
 [3 6]]
Transposed shape: (3, 2)

Data type of the array: int64

Array with float data type:
 [[1. 2. 3.]
 [4. 5. 6.]]
New data type: float64


Mathematical and statistical functions.

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)

# Sum of elements
print("Sum of elements:", np.sum(arr))

# Mean of elements
print("Mean of elements:", np.mean(arr))

# Standard deviation
print("Standard deviation:", np.std(arr))

# Maximum and minimum elements
print("Maximum element:", np.max(arr))
print("Minimum element:", np.min(arr))


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Sum of elements: 55
Mean of elements: 5.5
Standard deviation: 2.8722813232690143
Maximum element: 10
Minimum element: 1


Linear Algebra

In [12]:
# Matrix multiplication
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)
matrix_product2 = matrix_a @ matrix_b
print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)
print("\nMatrix product (A * B):\n", matrix_product)
print("\nAnother way to calculate matrix product (A * B):\n", matrix_product2)

# Element-wise multiplication (Hadamard product)
element_wise_product = matrix_a * matrix_b
print("\nElement-wise product (A * B):\n", element_wise_product)

# Transpose of a matrix
transposed_matrix_a = matrix_a.T
print("\nTranspose of Matrix A:\n", transposed_matrix_a)

# Inverse of a matrix
try:
    inverse_matrix_a = np.linalg.inv(matrix_a)
    print("\nInverse of Matrix A:\n", inverse_matrix_a)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and does not have an inverse.")

# Determinant of a matrix
determinant_matrix_a = np.linalg.det(matrix_a)
print("\nDeterminant of Matrix A:", determinant_matrix_a)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Matrix product (A * B):
 [[19 22]
 [43 50]]

Another way to calculate matrix product (A * B):
 [[19 22]
 [43 50]]

Element-wise product (A * B):
 [[ 5 12]
 [21 32]]

Transpose of Matrix A:
 [[1 3]
 [2 4]]

Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of Matrix A: -2.0000000000000004
